Starting ssh (via systemctl): ssh.service.
Stopping namenodes on [master]
Stopping datanodes
Stopping secondary namenodes [market2-Latitude-7390-2-in-1]
Starting namenodes on [master]
Starting datanodes
Starting secondary namenodes [market2-Latitude-7390-2-in-1]
WARNING: YARN_CONF_DIR has been replaced by HADOOP_CONF_DIR. Using value of YARN_CONF_DIR.
Starting resourcemanager
WARNING: YARN_CONF_DIR has been replaced by HADOOP_CONF_DIR. Using value of YARN_CONF_DIR.
resourcemanager is running as process 7119.  Stop it first.
Starting nodemanagers
WARNING: YARN_CONF_DIR has been replaced by HADOOP_CONF_DIR. Using value of YARN_CONF_DIR.
dmarket
__init__.py
manage.py
services
mkdir: `/shared': File exists
mkdir: `/shared/log': File exists
System check identified some issues:

WARNINGS:
services.Machine.start_time: (fields.W161) Fixed default value provided.
	HINT: It seems you set a fixed date / time / datetime value as default for this field. This may not be what you want. If you want to have the current date as default, use `django.utils.timezone.now`
No conflicts detected to merge.
System check identified some issues:

WARNINGS:
services.Machine.start_time: (fields.W161) Fixed default value provided.
	HINT: It seems you set a fixed date / time / datetime value as default for this field. This may not be what you want. If you want to have the current date as default, use `django.utils.timezone.now`
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_cron, services, sessions, sites
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
org.apache.spark.deploy.history.HistoryServer running as process 10352.  Stop it first.
cron: can't lock /var/run/crond.pid, otherpid may be 916: Resource temporarily unavailable
System check identified some issues:

WARNINGS:
services.Machine.start_time: (fields.W161) Fixed default value provided.
	HINT: It seems you set a fixed date / time / datetime value as default for this field. This may not be what you want. If you want to have the current date as default, use `django.utils.timezone.now`

System check identified 1 issue (0 silenced).
[20/Nov/2019 06:37:09] "GET /login/?next=/ HTTP/1.1" 200 1041
Not Found: /favicon.ico
[20/Nov/2019 06:37:09] "GET /favicon.ico HTTP/1.1" 404 2568
[20/Nov/2019 06:41:46] "GET /login/?next=/ HTTP/1.1" 200 1041
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /login/
[20/Nov/2019 06:42:08] "POST /login/ HTTP/1.1" 400 78487
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /services/machine/list/
[20/Nov/2019 06:42:08] "GET /services/machine/list/ HTTP/1.1" 400 77952
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:35] "GET /signup/ HTTP/1.1" 400 77787
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:35] "POST /signup/ HTTP/1.1" 400 78640
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /services/machine/list/
[20/Nov/2019 06:44:35] "GET /services/machine/list/ HTTP/1.1" 400 77952
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:43] "GET /signup/ HTTP/1.1" 400 77787
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:43] "POST /signup/ HTTP/1.1" 400 78640
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /services/machine/list/
[20/Nov/2019 06:44:43] "GET /services/machine/list/ HTTP/1.1" 400 77952
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:44] "GET /signup/ HTTP/1.1" 400 77787
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:44] "POST /signup/ HTTP/1.1" 400 78640
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /services/machine/list/
[20/Nov/2019 06:44:44] "GET /services/machine/list/ HTTP/1.1" 400 77952
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:44] "GET /signup/ HTTP/1.1" 400 77787
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:44] "POST /signup/ HTTP/1.1" 400 78640
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /services/machine/list/
[20/Nov/2019 06:44:44] "GET /services/machine/list/ HTTP/1.1" 400 77952
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:44] "GET /signup/ HTTP/1.1" 400 77787
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:45] "POST /signup/ HTTP/1.1" 400 78640
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /services/machine/list/
[20/Nov/2019 06:44:45] "GET /services/machine/list/ HTTP/1.1" 400 77952
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:45] "GET /signup/ HTTP/1.1" 400 77787
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:45] "POST /signup/ HTTP/1.1" 400 78640
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /services/machine/list/
[20/Nov/2019 06:44:45] "GET /services/machine/list/ HTTP/1.1" 400 77952
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:45] "GET /signup/ HTTP/1.1" 400 77787
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:45] "POST /signup/ HTTP/1.1" 400 78640
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /services/machine/list/
[20/Nov/2019 06:44:45] "GET /services/machine/list/ HTTP/1.1" 400 77952
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:45] "GET /signup/ HTTP/1.1" 400 77787
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:45] "POST /signup/ HTTP/1.1" 400 78640
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /services/machine/list/
[20/Nov/2019 06:44:45] "GET /services/machine/list/ HTTP/1.1" 400 77952
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:45] "GET /signup/ HTTP/1.1" 400 77787
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:44:45] "POST /signup/ HTTP/1.1" 400 78640
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /services/machine/list/
[20/Nov/2019 06:44:45] "GET /services/machine/list/ HTTP/1.1" 400 77952
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:45:16] "GET /signup/ HTTP/1.1" 400 77787
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /signup/
[20/Nov/2019 06:45:16] "POST /signup/ HTTP/1.1" 400 78640
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /services/machine/list/
[20/Nov/2019 06:45:16] "GET /services/machine/list/ HTTP/1.1" 400 77952
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /
[20/Nov/2019 06:52:40] "GET / HTTP/1.1" 400 78209
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[20/Nov/2019 06:52:40] "GET /favicon.ico HTTP/1.1" 400 78142
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /
[20/Nov/2019 06:54:36] "GET / HTTP/1.1" 400 78209
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[20/Nov/2019 06:54:37] "GET /favicon.ico HTTP/1.1" 400 78142
[20/Nov/2019 08:04:27] "GET / HTTP/1.1" 302 0
[20/Nov/2019 08:04:27] "GET /login?next=/ HTTP/1.1" 301 0
[20/Nov/2019 08:04:27] "GET /login/?next=/ HTTP/1.1" 200 1041
Not Found: /favicon.ico
[20/Nov/2019 08:04:27] "GET /favicon.ico HTTP/1.1" 404 2565
[20/Nov/2019 08:06:57] "GET /login/?next=/ HTTP/1.1" 200 1041
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /
[20/Nov/2019 08:07:05] "GET / HTTP/1.1" 400 78209
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /login/
[20/Nov/2019 08:17:12] "POST /login/ HTTP/1.1" 400 78483
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /services/machine/list/
[20/Nov/2019 08:17:12] "GET /services/machine/list/ HTTP/1.1" 400 77948
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /login/
[20/Nov/2019 08:27:36] "POST /login/ HTTP/1.1" 400 78483
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /services/machine/list/
[20/Nov/2019 08:38:25] "GET /services/machine/list/ HTTP/1.1" 400 77948
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /login/
[20/Nov/2019 08:39:43] "POST /login/ HTTP/1.1" 400 78483
[20/Nov/2019 08:42:29] "GET /login/?next=/ HTTP/1.1" 200 1041
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /login/
[20/Nov/2019 08:45:27] "POST /login/ HTTP/1.1" 400 78483
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /services/machine/list/
[20/Nov/2019 08:45:27] "GET /services/machine/list/ HTTP/1.1" 400 77948
Invalid HTTP_HOST header: '192.168.1.12:8000'. You may need to add '192.168.1.12' to ALLOWED_HOSTS.
Bad Request: /login/
[20/Nov/2019 08:46:11] "POST /login/ HTTP/1.1" 400 78483
[20/Nov/2019 08:47:05] "GET /login/?next=/ HTTP/1.1" 200 1041
Not Found: /favicon.ico
[20/Nov/2019 08:47:05] "GET /favicon.ico HTTP/1.1" 404 2565
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f39d6558940>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='master', port=8000): Max retries exceeded with url: /services/machine/init_cluster/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f39d6558940>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/init_cluster.py", line 7, in <module>
    response = client.post(url)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 567, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='master', port=8000): Max retries exceeded with url: /services/machine/init_cluster/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f39d6558940>: Failed to establish a new connection: [Errno 111] Connection refused',))
